### ISSUE TITLE
Create JupyterHub unity-marketplace metadata.json

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-ads#1] opened 2023-07-12 15:46 UTC

**Comment by GodwinShen** [comment] 2024-05-28 16:22
@mcduffie ping for status.

**Comment by galenatjpl** [comment] 2024-09-11 20:50
@mcduffie Hi! @pymonger will be working on creating this manifest.json

**Comment by galenatjpl** [comment] 2024-10-31 20:35
I'm going to close this ticket, since it's a duplicate of https://github.com/unity-sds/unity-cs/issues/491

**Closed as completed by galenatjpl** 2024-10-31 20:35 UTC
Labels: U-ADS, U-CS
